- hosts: all
  vars:
    server_jar_url: "https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar"
    base_path: "/var/minecraft"
  tasks:
    - name: Add Minecraft user
      ansible.builtin.user:
        name: minecraft
        comment: Minecraft Server Runner

    - name: Upgrade apt
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        purge: true
    
    - name: Install JDK
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present

    - name: Create Directory
      ansible.builtin.file:
        path: "{{ base_path }}"
        state: directory
        owner: minecraft
        group: minecraft

    - name: Copy eula.txt
      ansible.builtin.copy:
        src: ./files/eula.txt
        dest: "{{ base_path}}/eula.txt"
        owner: minecraft
        group: minecraft

    - name: Copy server.properties 
      ansible.builtin.copy:
        src: ./files/server.properties
        dest: "{{ base_path}}/server.properties"
        owner: minecraft
        group: minecraft

    - name: Copy Whitelist 
      ansible.builtin.copy:
        src: ./files/whitelist.json
        dest: "{{ base_path}}/whitelist.json"
        owner: minecraft
        group: minecraft

    - name: Copy Ops 
      ansible.builtin.copy:
        src: ./files/ops.json
        dest: "{{ base_path}}/ops.json"
        owner: minecraft
        group: minecraft

    - name: Download Server Jar 
      get_url:
        url: "{{ server_jar_url }}"
        dest: "{{ base_path }}/server.jar"
        owner: minecraft
        group: minecraft

    - name: Copy Service File
      ansible.builtin.copy:
        src: ./files/minecraft.service
        dest: "/etc/systemd/system/minecraft.service"
        owner: minecraft
        group: minecraft

    - name: Enable Minecraft Service
      ansible.builtin.systemd_service:
        name: minecraft
        enabled: true
        state: started
        name: minecraft
